/**
 * Auto-generated CHASIDE questions list from the official 98-question test.
 */

export interface ChasideQuestion {
  id: number;
  category: 'C' | 'H' | 'A' | 'S' | 'I' | 'D' | 'E';
  text: string;
}

export const CHASIDE_QUESTIONS_FULL: ChasideQuestion[] = [
  { id: 1, category: 'C', text: 'Me gustaría trabajar escribiendo artículos en la sección económica de un diario.' },
  { id: 2, category: 'C', text: 'Me ofrecería voluntario para organizar la despedida de soltero de un amigo.' },
  { id: 3, category: 'A', text: 'Me gustaría dirigir o diseñar un nuevo proyecto urbanístico.' },
  { id: 4, category: 'C', text: 'Siempre tengo una visión optimista cuando me enfrento a la frustración.' },
  { id: 5, category: 'D', text: 'Me gustaría trabajar ayudando a personas que han sufrido un accidente o han sido atacadas por delincuentes.' },
  { id: 6, category: 'I', text: 'Cuando era pequeño sentía curiosidad por descubrir cómo estaban hechos mis juguetes.' },
  { id: 7, category: 'C', text: 'Me interesan más los misterios de la naturaleza que los secretos de la tecnología.' },
  { id: 8, category: 'S', text: 'Presto atención cuando mis amigos me cuentan sus problemas.' },
  { id: 9, category: 'H', text: 'Me ofrezco a aclarar las dudas de mis compañeros cuando no entienden algo.' },
  { id: 10, category: 'C', text: 'Soy exigente y crítico con mis compañeros cuando trabajo en equipo.' },
  { id: 11, category: 'A', text: 'Me gusta resolver rompecabezas o montar puzzles.' },
  { id: 12, category: 'C', text: 'Me gustaría conocer la diferencia entre macroeconomía y microeconomía.' },
  { id: 13, category: 'C', text: 'Llevar uniforme me hace sentir importante.' },
  { id: 14, category: 'D', text: 'Me gustaría participar en un espectáculo de acrobacias aéreas.' },
  { id: 15, category: 'C', text: 'Organizo mis gastos para que me llegue el dinero hasta el siguiente día de cobro.' },
  { id: 16, category: 'S', text: 'Tengo facilidad para convencer a los demás de la validez de mis argumentos.' },
  { id: 17, category: 'E', text: 'Me gustaría estar al corriente de los últimos descubrimientos sobre el origen del universo.' },
  { id: 18, category: 'C', text: 'Cuando se presenta una emergencia actúo con rapidez.' },
  { id: 19, category: 'I', text: 'Cuando tengo que resolver un problema matemático, insisto hasta dar con la solución.' },
  { id: 20, category: 'C', text: 'Aceptaría gestionar una instalación deportiva.' },
  { id: 21, category: 'A', text: 'Soy el alma de las fiestas.' },
  { id: 22, category: 'C', text: 'Los detalles son tan importantes como el conjunto.' },
  { id: 23, category: 'S', text: 'Me sentiría a gusto trabajando en el ámbito sanitario.' },
  { id: 24, category: 'E', text: 'Me gustaría trabajar en el mantenimiento del orden en el caso de disturbios o sucesos catastróficos.' },
  { id: 25, category: 'H', text: 'Me pasaría horas leyendo un libro que me interesa.' },
  { id: 26, category: 'C', text: 'Planifico mis tareas concienzudamente antes de ponerme con ellas.' },
  { id: 27, category: 'I', text: 'Tengo una relación casi personal con mi ordenador.' },
  { id: 28, category: 'A', text: 'Me gusta hacer figuras con arcilla.' },
  { id: 29, category: 'I', text: 'Normalmente, ayudo a los invidentes o a las personas que lo necesitan a cruzar la calle.' },
  { id: 30, category: 'C', text: 'Creo que es importante que se fomente la participación activa y la actitud crítica desde la educación secundaria.' },
  { id: 31, category: 'D', text: 'Creo que que las mujeres deberían formar parte de las fuerzas armadas con las mismas condiciones que los hombres.' },
  { id: 32, category: 'E', text: 'Me gustaría desarrollar nuevas técnicas para investigar enfermedades a través del microscopio.' },
  { id: 33, category: 'S', text: 'Participaría en una campaña de prevención contra enfermedades como el sida.' },
  { id: 34, category: 'H', text: 'Me interesan los temas relacionados con el pasado y a la evolución del hombre.' },
  { id: 35, category: 'E', text: 'Me gustaría participar en un proyecto de investigación sobre los movimientos sísmicos y sus consecuencias.' },
  { id: 36, category: 'C', text: 'Realizo actividad física regularmente fuera del horario escolar.' },
  { id: 37, category: 'D', text: 'Me interesan las actividades con mucha acción en las que hay que actuar con rapidez ante un imprevisto o un peligro.' },
  { id: 38, category: 'I', text: 'Me ofrecería para colaborar como voluntario en los programas espaciales de la NASA.' },
  { id: 39, category: 'C', text: 'Prefiero el trabajo manual al intelectual.' },
  { id: 40, category: 'C', text: 'Estaría dispuesto a renunciar a mi tiempo libre para ejercer como voluntario.' },
  { id: 41, category: 'H', text: 'Me gustaría participar en una investigación sobre la violencia en el fútbol.' },
  { id: 42, category: 'E', text: 'Me gustaría compaginar mis estudios con un trabajo en un laboratorio.' },
  { id: 43, category: 'D', text: 'Arriesgaría mi vida para salvar la de otras personas aunque no las conozca.' },
  { id: 44, category: 'S', text: 'Me gustaría aprender primeros auxilios.' },
  { id: 45, category: 'A', text: 'Soy capaz de repetir algo las veces que haga falta hasta que me salga bien.' },
  { id: 46, category: 'C', text: 'Organizo mi horario cada día para poder cumplir con todas mis tareas.' },
  { id: 47, category: 'I', text: 'Me gustaría aprender a fabricar las herramientas o las piezas de las máquinas con las que trabajo.' },
  { id: 48, category: 'D', text: 'No me importaría tener una profesión en la tuviera que estar varios meses alejado de mi familia.' },
  { id: 49, category: 'E', text: 'Estaría dispuesto a trasladarme a una zona rural para ejercer una profesión agrícola o ganadera.' },
  { id: 50, category: 'H', text: 'Cuando trabajo en grupo me gusta plantear ideas originales y que sean tenidas en cuenta.' },
  { id: 51, category: 'C', text: 'Me resulta fácil coordinar el trabajo en equipo.' },
  { id: 52, category: 'S', text: 'Me pareció interesante el estudio de las ciencias biológicas.' },
  { id: 53, category: 'C', text: 'Me sentiría a gusto como responsable del departamento comercial de una gran empresa.' },
  { id: 54, category: 'E', text: 'Me gustaría formar parte de un proyecto para desarrollar la principal actividad económica de mi región.' },
  { id: 55, category: 'C', text: 'Me interesa conocer las causas de determinados fenómenos, aunque no me repercutan directamente.' },
  { id: 56, category: 'H', text: 'He descubierto algún filósofo o escritor que expresó ideas con las que me identifico.' },
  { id: 57, category: 'A', text: 'Me gustaría que me regalaran algún instrumento musical por mi cumpleaños.' },
  { id: 58, category: 'C', text: 'Estaría dispuesto a colaborar para mantener el orden en lugares públicos.' },
  { id: 59, category: 'C', text: 'Creo que mis ideas son importantes y hago todo lo posible para ponerlas en práctica.' },
  { id: 60, category: 'I', text: 'Cuando se estropea algo en casa, intento repararlo.' },
  { id: 61, category: 'E', text: 'Me gustaría formar parte de un equipo de trabajo para la conservación de especies en vías de extinción.' },
  { id: 62, category: 'S', text: 'Me gustaría leer revistas con los últimos avances científicos y tecnológicos en el área de la salud.' },
  { id: 63, category: 'H', text: 'Me parece importante preservar las raíces culturales de nuestro país.' },
  { id: 64, category: 'C', text: 'Me gustaría hacer algo que ayude a lograr una distribución más justa de la riqueza.' },
  { id: 65, category: 'A', text: 'Me gustaría hacer tareas de mantenimiento y apoyo en un barco.' },
  { id: 66, category: 'C', text: 'Creo que un país debe disponer de la tecnología militar más avanzada cueste lo que cueste.' },
  { id: 67, category: 'H', text: 'La libertad y la justicia son valores fundamentales en mi vida.' },
  { id: 68, category: 'E', text: 'Me gustaría trabajar en el departamento de control de calidad de una empresa de productos alimentarios.' },
  { id: 69, category: 'C', text: 'Creo que un sistema de salud pública universal y gratuito debe ser un derecho fundamental.' },
  { id: 70, category: 'H', text: 'Me gustaría participar en la investigación de nuevas vacunas.' },
  { id: 71, category: 'E', text: 'Cuando trabajo en equipo, me gusta llevar la voz cantante.' },
  { id: 72, category: 'C', text: 'Si veo que dos amigos discuten, me ofrezco como mediador.' },
  { id: 73, category: 'D', text: 'Creo que el ejército debe estar formado por soldados profesionales.' },
  { id: 74, category: 'H', text: 'Lucharía por una causa justa hasta las últimas consecuencias.' },
  { id: 75, category: 'I', text: 'Me gustaría llevar a cabo una investigación científica sobre cultivos agrícolas.' },
  { id: 76, category: 'A', text: 'Soy capaz de rediseñar ropa pasada de moda para un evento.' },
  { id: 77, category: 'E', text: 'Me gustaría visitar un observatorio astronómico para ver de cerca cómo funcionan los instrumentos.' },
  { id: 78, category: 'C', text: 'Me gustaría dirigir el departamento de importación y exportación de una empresa.' },
  { id: 79, category: 'C', text: 'Me siento incómodo cuando entro en un sitio nuevo con gente desconocida.' },
  { id: 80, category: 'C', text: 'Resulta gratificante trabajar con niños.' },
  { id: 81, category: 'A', text: 'Estaría dispuesto a diseñar un cartel informativo de una campaña para concienciar sobre el sida.' },
  { id: 82, category: 'C', text: 'Podría dirigir un grupo de teatro independiente.' },
  { id: 83, category: 'I', text: 'Enviaría mi curriculum a una empresa del sector automovilístico que busca un gerente para su área de producción.' },
  { id: 84, category: 'A', text: 'Estaría dispuesto a participar en un grupo de las fuerzas armadas que realiza misiones internacionales.' },
  { id: 85, category: 'C', text: 'Estaría dispuesto a trabajar como auditor contable para pagarme los estudios.' },
  { id: 86, category: 'C', text: 'Soy de los que defienden las causas perdidas.' },
  { id: 87, category: 'S', text: 'Estaría dispuesto a colaborar en una campaña de ayuda en caso de una epidemia.' },
  { id: 88, category: 'E', text: 'Sé lo que significan las siglas ADN y ARN.' },
  { id: 89, category: 'H', text: 'Estaría dispuesto a desarrollar una profesión que implicara conocer un idioma extranjero para desempeñar mis funciones.' },
  { id: 90, category: 'I', text: 'Prefiero trabajar con maquinaria que interactuando con gente.' },
  { id: 91, category: 'C', text: 'Me gustaría ser asesor contable de una empresa importante.' },
  { id: 92, category: 'C', text: 'Me ofrecería a cuidar a una persona enferma si se tratara de una causa solidaria.' },
  { id: 93, category: 'E', text: 'Me interesa investigar sobre los misterios del universo como por ejemplo los agujeros negros.' },
  { id: 94, category: 'C', text: 'Trabajo mejor solo que en grupo.' },
  { id: 95, category: 'C', text: 'No me importaría dedicar parte de mi tiempo para ayudar a personas necesitadas.' },
  { id: 96, category: 'A', text: 'Presto atención a los detalles estéticos cuando escojo mi ropa o decoro un espacio.' },
  { id: 97, category: 'I', text: 'Me gustaría trabajar dirigiendo la construcción de una central hidroeléctrica.' },
  { id: 98, category: 'C', text: 'Sé lo que significan las siglas PIB.' },
];
