export { CHASIDE_QUESTIONS_FULL, type ChasideQuestion } from './chaside-questions.generated';

export const CHASIDE_AREAS = {
  C: {
    name: 'Área Administrativa',
    description: 'Organización, supervisión, orden, análisis y síntesis',
    characteristics: [
      'Organización',
      'Supervisión',
      'Orden',
      'Análisis y síntesis',
      'Colaboración',
      'Cálculo',
      'Persuasivo',
      'Objetivo',
      'Práctico',
      'Tolerante',
      'Responsable',
      'Ambicioso',
    ],
    careerExamples: [
      'Contador Público',
      'Administración de Empresas',
      'Economía',
      'Contabilidad',
      'Finanzas',
      'Auditoría',
      'Gestión Empresarial',
    ],
  },
  H: {
    name: 'Área de Humanidades y Ciencias Sociales y Jurídicas',
    description: 'Análisis lingüístico, justicia, orden, relación de hechos',
    characteristics: [
      'Precisión Verbal',
      'Organización',
      'Relación de hechos',
      'Lingüística',
      'Orden',
      'Justicia',
      'Responsable',
      'Justo',
      'Conciliador',
      'Persuasivo',
      'Sagaz',
      'Imaginativo',
    ],
    careerExamples: [
      'Derecho',
      'Sociología',
      'Filosofía',
      'Educación',
      'Comunicación Social',
      'Periodismo',
      'Historia',
    ],
  },
  A: {
    name: 'Área Artística',
    description: 'Estético, armónico, manual, visual, creativo',
    characteristics: [
      'Estético',
      'Armónico',
      'Manual',
      'Visual',
      'Auditivo',
      'Sensible',
      'Imaginativo',
      'Creativo',
      'Detallista',
      'Innovador',
      'Intuitivo',
    ],
    careerExamples: [
      'Diseño Gráfico',
      'Arquitectura',
      'Artes Plásticas',
      'Música',
      'Danza',
      'Cine y Audiovisual',
      'Moda y Diseño Textil',
    ],
  },
  S: {
    name: 'Área de Ciencias de la Salud',
    description: 'Asistencia, investigación, precisión, ayuda, altruismo',
    characteristics: [
      'Asistir',
      'Investigar',
      'Precisión',
      'Percepción',
      'Análisis',
      'Ayudar',
      'Altruista',
      'Solidario',
      'Paciente',
      'Comprensivo',
      'Respetuoso',
      'Persuasivo',
    ],
    careerExamples: [
      'Medicina',
      'Enfermería',
      'Psicología',
      'Odontología',
      'Farmacia',
      'Terapia Física',
      'Nutrición',
    ],
  },
  I: {
    name: 'Área de Enseñanzas Técnicas',
    description: 'Cálculo, manual, precisión, planificación, análisis',
    characteristics: [
      'Cálculo',
      'Científico',
      'Manual',
      'Exactitud',
      'Planificar',
      'Preciso',
      'Práctico',
      'Crítico',
      'Analítico',
      'Rígido',
    ],
    careerExamples: [
      'Ingeniería de Sistemas',
      'Ingeniería Industrial',
      'Ingeniería Mecánica',
      'Ingeniería Civil',
      'Mecatrónica',
      'Tecnología en Informática',
    ],
  },
  D: {
    name: 'Área de Defensa y Seguridad',
    description: 'Justicia, equidad, colaboración, liderazgo, valentía',
    characteristics: [
      'Justicia',
      'Equidad',
      'Colaboración',
      'Espíritu de equipo',
      'Liderazgo',
      'Arriesgado',
      'Solidario',
      'Valiente',
      'Agresivo',
      'Persuasivo',
    ],
    careerExamples: [
      'Ciencias Militares',
      'Policía',
      'Seguridad Pública',
      'Bomberos',
      'Seguridad Industrial',
      'Defensa Civil',
    ],
  },
  E: {
    name: 'Área de Ciencias Experimentales',
    description: 'Investigación, orden, análisis, clasificación, metodología',
    characteristics: [
      'Investigación',
      'Orden',
      'Organización',
      'Análisis y Síntesis',
      'Cálculo numérico',
      'Clasificar',
      'Metódico',
      'Analítico',
      'Observador',
      'Introvertido',
      'Paciente',
      'Seguro',
    ],
    careerExamples: [
      'Biología',
      'Química',
      'Física',
      'Geología',
      'Biotecnología',
      'Ciencias del Ambiente',
      'Investigación Científica',
    ],
  },
} as const;
